# Generated by Django 4.2.4 on 2023-08-09 13:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0002_comment_post_delete_choice_delete_question_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="author",
        ),
    ]
